name: Deploy to test

on:
  workflow_dispatch:
    inputs:
      environment_manual:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - test 1
          - test 2
      branch:
        description: 'Branch to deploy'
        required: false
      dry_run:
        description: 'Dry run: no real deployment performed'
        type: boolean
        required: false

jobs:
  deploy-to-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_manual }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          which python
      - run: |
          echo "Deployed branch ${{inputs.branch}} to ${{ inputs.environment }} environment"
      - run: |
          echo "${{ toJSON(inputs) }}"
      - run: |
          echo "${{ toJSON(github) }}"
  helth-check:
    needs: deploy-to-env
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_auto }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          which python
      - run: |
          echo "Verifying the service heals in ${{ inputs.environment }} environment"
  canaries-check:
    needs: helth-check
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_auto }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: |
          which python
      - run: |
          echo "Verifying the service heals in ${{ inputs.environment }} environment"
